# Generated by Django 3.2.16 on 2022-12-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bwblog', '0005_comment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
