# Generated by Django 3.2.16 on 2023-02-02 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bwblog', '0009_commentdisc_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentdisc',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bwblog.discussion'),
        ),
    ]
