# Generated by Django 3.2.16 on 2023-02-08 20:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bwblog', '0014_auto_20230208_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='dislikes',
        ),
        migrations.AddField(
            model_name='discussion',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='likes',
        ),
        migrations.AddField(
            model_name='discussion',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
