# Generated by Django 3.2.16 on 2023-02-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwblog', '0015_auto_20230208_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='dislikes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discussion',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
