# Generated by Django 3.2.16 on 2023-02-09 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bwblog', '0016_auto_20230208_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='dislikes_count',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='likes_count',
        ),
    ]
