# Generated by Django 3.2.16 on 2023-02-12 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bwblog', '0017_auto_20230209_1725'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
